<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Denosumab_img-circle profile-img thumb-midsm</name>
   <tag></tag>
   <elementGuidId>33176203-006c-4e50-b82f-4baf40a50fa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-circle.profile-img.thumb-midsm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='dropdownLink1']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c0c80156-1452-4bf5-acf7-1f9f3fd6f93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-circle profile-img thumb-midsm</value>
      <webElementGuid>e9b65a35-7875-4245-9ba7-6d48416d0e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//sandoz-staging.integratedge.com/files/profilepic/1/ip_1_1442_641978e5f39c2.jpg</value>
      <webElementGuid>2ad99d6c-ac55-4a25-89ee-e05f201ddff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>User Pic</value>
      <webElementGuid>e481b2fb-3a8c-4460-9946-6c9305a93183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownLink1&quot;)/a[@class=&quot;dropdown-toggle clearfix&quot;]/img[@class=&quot;img-circle profile-img thumb-midsm&quot;]</value>
      <webElementGuid>ff3597e8-eade-480d-a563-e907c006cc13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='dropdownLink1']/a/img</value>
      <webElementGuid>41d5586c-f652-414d-b0f0-6bf9f3b9ffd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='User Pic']</value>
      <webElementGuid>5816113d-31df-468e-a8fa-3dc00c47c5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/img</value>
      <webElementGuid>7955a03c-6f0d-44e6-a3a0-e74fdb654cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//sandoz-staging.integratedge.com/files/profilepic/1/ip_1_1442_641978e5f39c2.jpg' and @alt = 'User Pic']</value>
      <webElementGuid>f9af9284-1e08-4c48-8937-41c9ab78fe38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
