<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New User_yt0</name>
   <tag></tag>
   <elementGuidId>0a986c3b-7b4d-42cf-92d8-c91019fca1fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signIn1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signIn1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55e362d1-f8c9-4a57-951f-472b73cc73b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>c98f22f8-62cc-4e67-a5c9-72b53e682270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn orange-soft pull-right</value>
      <webElementGuid>906343d0-fca3-430a-973a-fcfd06d89fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signIn1</value>
      <webElementGuid>6af1c1bf-baa2-47e4-9968-036495dc6ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e24d1d5c-94e4-405e-b230-be2f6579cd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>yt0</value>
      <webElementGuid>9abf475f-fc99-4c9c-a2a9-77a9992481f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signIn1&quot;)</value>
      <webElementGuid>da68e84e-d074-4056-bea9-545dbec19fc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signIn1']</value>
      <webElementGuid>7f289d2e-8e2f-488c-a712-30f25ea94fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signin']/div[4]/div/input</value>
      <webElementGuid>acbbc7aa-4fce-4591-beb0-068e57f78c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>ba7f18c6-5faf-42f1-8ee7-a60df8e28236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signIn1' and @type = 'submit' and @name = 'yt0']</value>
      <webElementGuid>a223af7c-fb13-4ee9-8c47-5e157f75a955</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
