<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sandoz_LoginFormpassword</name>
   <tag></tag>
   <elementGuidId>19c9854e-6fd3-442c-a784-4e723acff53a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LoginForm_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoginForm_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1ced3f9-20da-44c1-b32c-08c6ca6c6f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6987005e-b673-40a5-9e38-17fa910262d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control bor-radi</value>
      <webElementGuid>68bb68ac-3968-4989-9976-a09aca9612bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>68260ea4-4a43-4c99-94a4-c41d7e0f234c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginForm[password]</value>
      <webElementGuid>b1bb8114-98d0-4594-ae5e-c0dce95f51d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginForm_password</value>
      <webElementGuid>aed9acdc-336b-4664-8b7a-9880c0177da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>aabc81b0-e017-44b1-bc45-ff0cfc143999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginForm_password&quot;)</value>
      <webElementGuid>707bae20-f9c8-4833-bb30-3df83b5e1236</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoginForm_password']</value>
      <webElementGuid>5dd338f7-fe95-4312-bc4d-27405fd0ff3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signin']/div[3]/div/input</value>
      <webElementGuid>13497c6c-bd50-43a3-868b-2c3b1680ba9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>df882a01-dfb1-433f-8a6e-44d3ce2a531e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Password' and @name = 'LoginForm[password]' and @id = 'LoginForm_password' and @type = 'password']</value>
      <webElementGuid>a085ce02-8c53-4f3a-8181-24deac53c288</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
