<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sandoz_LoginFormuser_name</name>
   <tag></tag>
   <elementGuidId>48c4ed5c-1c5c-463e-9cf0-4b21708cb7bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LoginForm_user_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoginForm_user_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cd6fd25-67f0-4b99-831f-eacec48e43fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7154f1e8-c195-4a21-b503-d81b076ab0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control bor-radi</value>
      <webElementGuid>871c4d6c-553b-4b62-901c-bdc5cc537353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>df68cf1a-e141-4531-bc27-5f8bb93b94ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginForm[user_name]</value>
      <webElementGuid>0af5b54a-dec4-4709-954d-36abd87aea4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginForm_user_name</value>
      <webElementGuid>0116efac-2acc-44d7-8503-5880f5c2ffc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4684dbf1-3e87-4eae-876b-5c7d61bf552f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginForm_user_name&quot;)</value>
      <webElementGuid>e3102503-f899-43fa-82eb-3b1db4317b18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoginForm_user_name']</value>
      <webElementGuid>88442d6e-a807-49a3-a402-7f53dfb00abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signin']/div[2]/div/input</value>
      <webElementGuid>fb4c3b22-a05b-4332-a340-d8296358adb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>a5f5787e-1f65-40ad-87cf-08e3e2672c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email Address' and @name = 'LoginForm[user_name]' and @id = 'LoginForm_user_name' and @type = 'text']</value>
      <webElementGuid>cfa8aa90-979d-42fe-b0b9-d4f0771b0cc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
