<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Pegfilgrastim</name>
   <tag></tag>
   <elementGuidId>04a277d4-d338-4a5a-bb49-9ba5dd0d51b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='customStyleDiv']/div/div/a/div[2]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>30e4e583-c00d-4cec-8173-ce253a00a5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pegfilgrastim</value>
      <webElementGuid>950b0959-2b02-484d-ad2d-3c6eaf6afc11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customStyleDiv&quot;)/div[@class=&quot;indication-box-main&quot;]/div[@class=&quot;indication-boxes&quot;]/a[1]/div[@class=&quot;interpage_panel_heading&quot;]/h2[1]</value>
      <webElementGuid>94afe06b-4eb0-49e1-9445-ce352f0dcb9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customStyleDiv']/div/div/a/div[2]/h2</value>
      <webElementGuid>44a5da31-d737-46fc-9a5c-d655ed4fa329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to the Sandoz CI Portal'])[1]/following::h2[1]</value>
      <webElementGuid>dd31dfb8-ded0-4c47-88ad-72ef2bd8c211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::h2[1]</value>
      <webElementGuid>eeb5ab88-d342-42d4-bfc2-99e193cc8dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filgrastim'])[1]/preceding::h2[1]</value>
      <webElementGuid>83656f78-6fbd-44ad-adb1-f88508f3665e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trastuzumab'])[1]/preceding::h2[2]</value>
      <webElementGuid>11c46892-c6b2-4198-bfd8-06cc454355b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pegfilgrastim']/parent::*</value>
      <webElementGuid>d6efd001-9002-4e56-b97d-1e2fdcb27676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>5ffa10b2-428e-4596-b196-17ef9eaa16ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Pegfilgrastim' or . = 'Pegfilgrastim')]</value>
      <webElementGuid>abbe0184-e378-4858-9c95-92302e9355b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
